### PR TITLE
fix: Various copyedits & design improvements

### PR DESCRIPTION
**Pull request by sarahmonster**
This is a WIP; updating Nautilus broke some of the styling & it probably requires more Nautilus work in order to get it working properly again.

### CODE REVIEW

**Comment by tofumatt** [comment]
If it helps at all, this is the comparison between those two versions of Nautilus: https://github.com/octopusthink/nautilus/compare/b5d2370637ad03bfff510cd61a57c8f8487865dc...4dea4dcd7dbbe6a03e3e812390f1dda3a920697f

**Comment by tofumatt** [comment]
I don't see many differences there, and wonder if something else is up. I'll have a look at this PR and see if I can diagnose the issue 🙂

**Comment by sarahmonster** [comment]
It looks like my styling is being overridden by other styles. I could brute-force it using an !important flag, but that's not a great long-term solution for obvious reasons.

1. Font-size applied to PageTitles (PageHeader 43)
2. Margins applied to Paragraphs (Argument 87)

**Comment by tofumatt** [comment]
The build failing is something unrelated and a weird dependency error. I'm working on fixing it now…

**Comment by tofumatt** [comment]
It's possible that Nautilus' [recent dependency on emotion](https://github.com/octopusthink/nautilus/issues/188) is causing this issue. We may not be able to rely on emotion as a non-peer-dependency for Nautilus… 😢 

This is supported by installing any version of Nautilus before https://github.com/octopusthink/nautilus/commit/0616b5ab1d0b285d27b091844721f431a673d853 and it building. Installing that commit or any commit after and the HTML build stage fails.

**Pull request merged**
